before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: main.go
    binary: etcdir
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"