env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - main: main.go
    binary: etcdir
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"